name: Integration Tests

on:
  push:
    branches:
      - main
      - 'feature/issue-*'
  pull_request:
    branches:
      - main
      - 'feature/issue-*'
  schedule:
      - cron: '20 8 * * *'
      - cron: '55 17 * * *'

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Create local.properties
        run: echo "sdk.dir=$ANDROID_HOME" > local.properties

      - name: Create debug keystore
        run: |
          keytool -genkey -v -keystore app/debug.keystore \
          -alias androiddebugkey -keyalg RSA -keysize 2048 -validity 10000 \
          -dname "CN=Android Debug,O=Android,C=US" \
          -storepass android -keypass android

      - name: Clone app repo
        run: git clone https://github.com/Fairies-Pixels/curlylab.git curlylab

      - name: Download env
        run: wget "https://downloader.disk.yandex.ru/disk/ac55d6be074e3b5a3c33ef0f9186c42e8cc194e55a1f3627ac2053461212f33d/69ca0309/dJMZ6Bla5hgccBI1MvRwdt7hQm0Rf9Hg-yfaKnOkLu0GsVmDhnf202gFmf9qPeVf-8nh0M6FCbZB8KwRP_8qSw%3D%3D?uid=0&filename=env.sh&disposition=attachment&hash=9LdiunMhqqrWuS0k8zevJLGy/LFjAensq5P2NUjsto/MOZmmlzHnkntOF5fCoMjDq/J6bpmRyOJonT3VoXnDag%3D%3D%3A&limit=0&content_type=text%2Fx-shellscript&owner_uid=1011034159&fsize=846&hid=4a24530babebe9e0e020f496eab2d736&media_type=compressed&tknv=v3" -O curlylab/docker/env.sh

      - name: Download model
        run: wget "https://downloader.disk.yandex.ru/disk/b42a7415a74660781994335ab130324e0d8455ad695b5a4ac588f20ecc6a60f7/69ca03fb/dJMZ6Bla5hgccBI1MvRwdqlNv7n3kJc6WHu_SlpBww1A-XDM5cGs0XyMANWTzCIIVEPKozJZ2gqLUDz6BgitVw%3D%3D?uid=0&filename=swa_convnext.pt&disposition=attachment&hash=PkZMpu754Bqqpd8WLMQcO3FqF1JyD51bCruwdji0vhBKl94WflRJt77E7KCtS95rq/J6bpmRyOJonT3VoXnDag%3D%3D%3A&limit=0&content_type=application%2Fzip&owner_uid=1011034159&fsize=350413157&hid=408ec0ba32625e264d7af6af7ebf9604&media_type=compressed&tknv=v3" -O curlylab/docker/swa_convnext.pt

      - name: Install docker-compose
        run: curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && chmod +x /usr/local/bin/docker-compose

      - name: pwd
        run: pwd

      - name: Bring up app
        run: pushd . && cd curlylab/docker && source startup.sh $JAVA_HOME && popd

      - name: Analyze network
        run: sleep 30 && ss -lt && ss -ltnp

      - name: Debug ip
        run: curl 127.0.0.1:8080/products && curl 127.0.0.1:8081/products

      - name: Run instrumentation tests
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: 33
          arch: x86_64
          profile: pixel
          cores: 2
          ram-size: 2048M
          force-avd-creation: true
          disable-animations: true
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none -no-snapshot -no-metrics
          script: |
            adb kill-server
            adb start-server
          
            adb wait-for-device
            sleep 30
          
            adb shell input keyevent 82 || true
          
            ./gradlew connectedAndroidTest
            
  integration-tests-report:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - name: Print report HTML
        run: cat /home/runner/work/curlylab-android/curlylab-android/app/build/reports/androidTests/connected/debug/index.html
