name: Integration Tests

on:
  push:
    branches:
      - main
      - 'feature/issue-*'
  pull_request:
    branches:
      - main
      - 'feature/issue-*'
  schedule:
      - cron: '20 8 * * *'
      - cron: '55 17 * * *'

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Create local.properties
        run: echo "sdk.dir=$ANDROID_HOME" > local.properties

      - name: Create debug keystore
        run: |
          keytool -genkey -v -keystore app/debug.keystore \
          -alias androiddebugkey -keyalg RSA -keysize 2048 -validity 10000 \
          -dname "CN=Android Debug,O=Android,C=US" \
          -storepass android -keypass android

      - name: Clone app repo
        run: git clone https://github.com/Fairies-Pixels/curlylab.git curlylab

      - name: Download env
        run: wget "https://downloader.disk.yandex.ru/disk/157d7ffb71f312abf413a910341e1d23fadf666d8cec765177a5713bf90af86e/69ca4df6/dJMZ6Bla5hgccBI1MvRwdt7hQm0Rf9Hg-yfaKnOkLu0GsVmDhnf202gFmf9qPeVf-8nh0M6FCbZB8KwRP_8qSw%3D%3D?uid=0&filename=env.sh&disposition=attachment&hash=9LdiunMhqqrWuS0k8zevJLGy/LFjAensq5P2NUjsto/MOZmmlzHnkntOF5fCoMjDq/J6bpmRyOJonT3VoXnDag%3D%3D%3A&limit=0&content_type=text%2Fx-shellscript&owner_uid=1011034159&fsize=846&hid=4a24530babebe9e0e020f496eab2d736&media_type=compressed&tknv=v3" -O curlylab/docker/env.sh

      - name: Download model
        run: wget "https://downloader.disk.yandex.ru/disk/079597c4c62c5a40d5adf959990e5dd5f5c9e1826442abc0ee271e6ec0bf8950/69ca4e29/dJMZ6Bla5hgccBI1MvRwdqlNv7n3kJc6WHu_SlpBww1A-XDM5cGs0XyMANWTzCIIVEPKozJZ2gqLUDz6BgitVw%3D%3D?uid=0&filename=swa_convnext.pt&disposition=attachment&hash=PkZMpu754Bqqpd8WLMQcO3FqF1JyD51bCruwdji0vhBKl94WflRJt77E7KCtS95rq/J6bpmRyOJonT3VoXnDag%3D%3D%3A&limit=0&content_type=application%2Fzip&owner_uid=1011034159&fsize=350413157&hid=408ec0ba32625e264d7af6af7ebf9604&media_type=compressed&tknv=v3" -O curlylab/docker/swa_convnext.pt

      - name: Install docker-compose
        run: curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && chmod +x /usr/local/bin/docker-compose

      - name: Bring up app
        run: pushd . && cd curlylab/docker && source startup.sh $JAVA_HOME && popd

      - name: Run instrumentation tests
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: 33
          arch: x86_64
          profile: pixel
          cores: 2
          ram-size: 2048M
          force-avd-creation: true
          disable-animations: true
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none -no-snapshot -no-metrics
          script: |
            adb kill-server
            adb start-server
          
            adb wait-for-device
            sleep 30
            
            adb shell ping -c 3 10.0.2.2
            adb shell curl http://10.0.2.2:8080/products
            
            adb shell input keyevent 82 || true
          
            ./gradlew connectedAndroidTest
            
      - name: Create report HTML
        if: always()
        run: zip -r report.zip /home/runner/work/curlylab-android/curlylab-android/app/build/reports/androidTests/connected/debug

      - name: Submit report HTML
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: report-archive
          path: report.zip
