name: Integration Tests

on:
  push:
    branches:
      - main
      - 'feature/issue-*'
  pull_request:
    branches:
      - main
      - 'feature/issue-*'
  schedule:
      - cron: '20 8 * * *'
      - cron: '55 17 * * *'

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - name: Download ftp
        run: wget "https://downloader.disk.yandex.ru/disk/537f04868ab6b4dc57d063f34d34003e2bde8d481a72e03092eab48279ab4c8f/69ca3fee/dJMZ6Bla5hgccBI1MvRwdhh5eIseETSuFY7-Ji9Sr33x3mJ2VGihnZCCkZMjbb2DLzSbOhSAxDF-zZn244cfPw%3D%3D?uid=0&filename=ftp.conf&disposition=attachment&hash=ApFrMmR%2Bm8BiVoR9HwPYYGCtrnz9Z4%2Bgt9RJapcsYibardWtgcgCfB2MdX5uRAvfq/J6bpmRyOJonT3VoXnDag%3D%3D%3A&limit=0&content_type=text%2Fplain&owner_uid=1011034159&fsize=59&hid=902f1aa1cb5e83b68c3134d25035942b&media_type=settings&tknv=v3" -O ftp.conf

      - name: ftp debug
        run: touch report.zip && ls && ftp -N ftp.conf -u "ftp://curlylab.ru/report.zip" report.zip

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Create local.properties
        run: echo "sdk.dir=$ANDROID_HOME" > local.properties

      - name: Create debug keystore
        run: |
          keytool -genkey -v -keystore app/debug.keystore \
          -alias androiddebugkey -keyalg RSA -keysize 2048 -validity 10000 \
          -dname "CN=Android Debug,O=Android,C=US" \
          -storepass android -keypass android

      - name: Run instrumentation tests
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: 33
          arch: x86_64
          profile: pixel
          cores: 2
          ram-size: 2048M
          force-avd-creation: true
          disable-animations: true
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none -no-snapshot -no-metrics
          script: |
            adb kill-server
            adb start-server
          
            adb wait-for-device
            sleep 30
          
            adb shell input keyevent 82 || true
          
            ./gradlew connectedAndroidTest
            
      - name: Create report HTML
        if: always()
        run: zip -r report.zip /home/runner/work/curlylab-android/curlylab-android/app/build/reports/androidTests/connected/debug && ftp -s ftp.conf curlylab.ru
